name: software_licensing
description: A library providing an expandible software licensing solution
version: 0.9.0
repository: https://github.com/atomiccity/software_licensing
issue_tracker: https://github.com/atomiccity/software_licensing/issues

environment:
  sdk: ^3.6.0

dependencies:
  pointycastle: ^3.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
